---
name: Sysbench validation workload
author: Arne Tarara <arne@green-coding.berlin>
description: Stress Container in 1 core steps for 90 seconds each and log SCI

services:
  gcb-alpine-sysbench:
    image: gcb_alpine_sysbench
    build: .

flow:
  - name: Stress
    container: gcb-alpine-stress
    commands:
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=1 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 1
        log-stdout: True
        read-sci-stdout: True
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=2 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 2
        log-stdout: True
        read-sci-stdout: True
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=3 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 3
        log-stdout: True
        read-sci-stdout: True
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=4 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 4
        log-stdout: True
        read-sci-stdout: True
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=5 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 5
        log-stdout: True
        read-sci-stdout: True
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=6 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 6
        log-stdout: True
        read-sci-stdout: True
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=7 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 7
        log-stdout: True
        read-sci-stdout: True
      - type: console
        command: sleep 120
        note: Sleep 120
      - type: console
        command: sysbench --cpu-max-prime=25000 --threads=8 --time=90 --test=cpu run --events=0 --rate=0 --debug=off | gawk '/total number of events:/{print "GMT_SCI_R="$NF}'
        note: Starting Sysbench 8
        log-stdout: True
        read-sci-stdout: True
