---
name: Stress Container progressively increasing in intervals
author: Arne Tarara <arne@green-coding.berlin>
description: Stress Container progressively increasing in intervals

services:
  gcb-ubuntu-stress:
    build:
      context: .
      dockerfile: Dockerfile_Ubuntu

flow:
  - name: Stress
    container: gcb-ubuntu-stress
    commands:
      - type: console
        command: bash /tmp/repo/stress-step-idle-cycle.sh
        note: Starting cycle
